stages:
  - test

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build
  before_script:
    - pip install -U -r ci/requirements.txt
  script:
    - python setup.py build_clib --debug
    - python setup.py build_ext  --debug --inplace
    - python -m coverage run -m unittest discover -v
  after_script:
    - python -m coverage xml
    - python -m coverage report
    - python -m codecov

# --- Stages -------------------------------------------------------------------

test:python3.6:
  image: python:3.6
  <<: *test

test:python3.7:
  image: python:3.7
  <<: *test

test:python3.8:
  image: python:3.8
  <<: *test

test:python3.9:
  image: python:3.9
  <<: *test
