stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build
  before_script:
    - $python -m pip install -U -r ci/requirements.txt
  script:
    - $python setup.py build_clib --debug
    - $python setup.py build_ext  --debug --inplace
    - $python -m coverage run -m unittest discover -v
  after_script:
    - $python -m coverage xml
    - $python -m coverage report
    - $python -m codecov

# --- Stages -------------------------------------------------------------------

test:python3.6:
  image: python:3.6
  environment:
    name: Python 3.6
    python: python
  <<: *test

test:python3.7:
  image: python:3.7
  environment:
    name: Python 3.7
    python: python
  <<: *test

test:python3.8:
  image: python:3.8
  environment:
    name: Python 3.8
    python: python
  <<: *test

test:python3.9:
  image: python:3.9
  environment:
    name: Python 3.9
    python: python
  <<: *test

test:pypy3.7:
  image: pypy:3.7
  environment:
    name: PyPy 3.7
    python: pypy3
  rules:
    allow_failure: true
  <<: *test
