stages:
  - test
  - bdist

variables:
  GIT_DEPTH: 100
  GIT_SUBMODULE_STRATEGY: recursive
  TWINE_USERNAME: gitlab-ci-token
  TWINE_PASSWORD: $CI_JOB_TOKEN

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build
  before_script:
    - $python -m pip install -U -r ci/requirements.txt
  script:
    - $python setup.py build_clib --debug
    - $python setup.py build_ext  --debug --inplace
    - $python -m coverage run -m unittest discover -v
  after_script:
    - $python -m coverage xml
    - $python -m coverage report
    - $python -m codecov
  artifacts:
    reports:
      cobertura: coverage.xml

.bdist: &bdist
  stage: bdist
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build
  before_script:
    - $python -m pip install -U -r ci/requirements.txt
    - VERSION=$($python setup.py --version)
    - NEW_VERSION=$(git describe --tags | sed "s/v${VERSION}-\\([0-9]\\+\\)-\\([0-9a-z]\\+\\)/$VERSION+\1.\2/g")
    - sed -i "s/${VERSION}/${NEW_VERSION}/g" pyhmmer/__init__.py
  script:
    - $python setup.py build_clib
    - $python setup.py build_ext
    - $python setup.py bdist_wheel
  after_script:
    - $python -m twine upload --repository-url https://git.embl.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*


# --- Stages -------------------------------------------------------------------

test:python3.6:
  image: quay.io/pypa/manylinux2010_x86_64
  environment:
    name: Python 3.6
  variables:
    python: /opt/python/cp36-cp36m/bin/python
  <<: *test

test:python3.7:
  image: quay.io/pypa/manylinux2010_x86_64
  environment:
    name: Python 3.7
  variables:
    python: /opt/python/cp37-cp37m/bin/python
  <<: *test

test:python3.8:
  image: quay.io/pypa/manylinux2010_x86_64
  environment:
    name: Python 3.8
  variables:
    python: /opt/python/cp38-cp38/bin/python
  <<: *test

test:python3.9:
  image: quay.io/pypa/manylinux2010_x86_64
  environment:
    name: Python 3.9
  variables:
    python: /opt/python/cp39-cp39/bin/python
  <<: *test

test:pypy3.7:
  image: pypywheels/manylinux2010-pypy_x86_64
  environment:
    name: PyPy 3.7
  variables:
    python: /opt/pypy/pypy3.7-7.3.3/bin/python
  rules:
    - allow_failure: true
  <<: *test


bdist:python3.6:
  image: quay.io/pypa/manylinux2010_x86_64
  dependencies:
    - test:python3.6
  environment:
    name: Python 3.6
  variables:
    python: /opt/python/cp36-cp36m/bin/python
  <<: *bdist

bdist:python3.7:
  image: quay.io/pypa/manylinux2010_x86_64
  dependencies:
    - test:python3.7
  environment:
    name: Python 3.7
  variables:
    python: /opt/python/cp37-cp37m/bin/python
  <<: *bdist

bdist:python3.8:
  image: quay.io/pypa/manylinux2010_x86_64
  dependencies:
    - test:python3.8
  environment:
    name: Python 3.8
  variables:
    python: /opt/python/cp38-cp38/bin/python
  <<: *bdist

bdist:python3.9:
  image: quay.io/pypa/manylinux2010_x86_64
  dependencies:
    - test:python3.9
  environment:
    name: Python 3.9
  variables:
    python: /opt/python/cp39-cp39/bin/python
  <<: *bdist

bdist:pypy3.7:
  image: pypywheels/manylinux2010-pypy_x86_64
  dependencies:
    - test:pypy3.7
  environment:
    name: PyPy 3.7
  variables:
    python: /opt/pypy/pypy3.7-7.3.3/bin/python
  rules:
    - allow_failure: true
  <<: *bdist
